name: Ask (random DM)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"  # 毎日 20:00 JST

    
permissions:
  contents: write

jobs:
  ask:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_BOT_USER_ID: ${{ secrets.SLACK_BOT_USER_ID }}
      ASK_COUNT: "3"
      EXCLUDE_USER_IDS: "U04RZV7Q6TU,U04RTBG352A,U04RZRKAYBV,U04SPL08SBA,U08L3P3HMU5,U04RX1PEYTF,U04SCJF3QHX"




    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python scripts/ask_random_dm.py
      
      - name: Show git status (debug)
        run: |
          git status
          git diff -- state/state.json || true

      - name: Commit state update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add state/state.json
          git commit -m "Update state (ask)" || echo "No changes"

      - name: Push
        run: |
          git push

